apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopssample-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DevopsSample
  template:
    metadata:
      labels:
        app: DevopsSample
    spec:
      containers:
      - name: dockersamplerepos
        image: dnsamplecr.azurecr.io/dockersamplerepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsna

---
apiVersion: v1
kind: Service
metadata:
  name: devopssample
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: DevopsSample
